
const decode_type_t  irType = SONY;

// The Sony device was just used for testing the device specific IR codes abstraction
#define IR_SONY_1            0x0000
#define IR_SONY_2            0x0001
#define IR_SONY_3            0x0002
#define IR_SONY_4            0x0003
#define IR_SONY_5            0x0004
#define IR_SONY_6            0x0005
#define IR_SONY_7            0x0006
#define IR_SONY_8            0x0007
#define IR_SONY_9            0x0008
#define IR_SONY_0            0x0009
#define IR_SONY_CH_UP        0x0010
#define IR_SONY_CH_DOWN      0x0011
#define IR_SONY_VOL_UP       0x0012
#define IR_SONY_VOL_DOWN     0x0013
#define IR_SONY_MUTE         0x0014
#define IR_SONY_POWER_TOGGLE 0x0015
#define IR_SONY_STOP         0x0018
#define IR_SONY_PAUSE        0x0019
#define IR_SONY_PLAY         0x001A
#define IR_SONY_REW          0x001B
#define IR_SONY_FWD          0x001C
#define IR_SONY_REC          0x0020
#define IR_SONY_BACK         0x0023
#define IR_SONY_BLUE         0x0024
#define IR_SONY_RED          0x0025
#define IR_SONY_GREEN        0x0026
#define IR_SONY_YELLOW       0x0027
#define IR_SONY_SUBTITLE     0x0028
#define IR_SONY_POWER_ON     0x002E
#define IR_SONY_POWER_OFF    0x002F
#define IR_SONY_RIGHT        0x0033
#define IR_SONY_LEFT         0x0034
#define IR_SONY_INFO         0x003A
#define IR_SONY_PREV         0x003B
#define IR_SONY_REPLAY       0x003C
#define IR_SONY_SKIP         0x003D
#define IR_SONY_GUIDE        0x005B
#define IR_SONY_SYNC_MENU    0x0058
#define IR_SONY_MENU         0x0060
#define IR_SONY_EXIT         0x0063
#define IR_SONY_OK           0x0065
#define IR_SONY_UP           0x0074
#define IR_SONY_DOWN         0x0075

//------------ Standard Logitech 880 buttons ---------------------
#define REMOTE_MUTE         IR_SONY_MUTE
#define REMOTE_VOL_UP       IR_SONY_VOL_UP
#define REMOTE_VOL_DOWN     IR_SONY_VOL_DOWN
#define REMOTE_ARROW_DOWN   IR_SONY_SUBTITLE
#define REMOTE_ARROW_UP     0
#define REMOTE_CH_DOWN      IR_SONY_CH_DOWN
#define REMOTE_CH_UP        IR_SONY_CH_UP
#define REMOTE_PREV         IR_SONY_PREV
#define REMOTE_UP           IR_SONY_UP
#define REMOTE_DOWN         IR_SONY_DOWN
#define REMOTE_LEFT         IR_SONY_LEFT
#define REMOTE_RIGHT        IR_SONY_RIGHT
#define REMOTE_OK           IR_SONY_OK
#define REMOTE_MENU         IR_SONY_MENU
#define REMOTE_EXIT         IR_SONY_EXIT
#define REMOTE_GUIDE        IR_SONY_GUIDE
#define REMOTE_INFO         IR_SONY_INFO
#define REMOTE_STOP         IR_SONY_STOP
#define REMOTE_REPLAY       IR_SONY_REPLAY
#define REMOTE_SKIP         IR_SONY_SKIP
#define REMOTE_PLAY         IR_SONY_PLAY
#define REMOTE_REC          IR_SONY_REC
#define REMOTE_REW          IR_SONY_REW
#define REMOTE_FWD          IR_SONY_FWD
#define REMOTE_PAUSE        IR_SONY_PAUSE
#define REMOTE_1            IR_SONY_1
#define REMOTE_2            IR_SONY_2
#define REMOTE_3            IR_SONY_3
#define REMOTE_4            IR_SONY_4
#define REMOTE_5            IR_SONY_5
#define REMOTE_6            IR_SONY_6
#define REMOTE_7            IR_SONY_7
#define REMOTE_8            IR_SONY_8
#define REMOTE_9            IR_SONY_9
#define REMOTE_0            IR_SONY_0
#define REMOTE_ENTER        IR_SONY_SYNC_MENU

// Additional buttons
#define REMOTE_POWER_TOGGLE IR_SONY_POWER_TOGGLE
#define REMOTE_POWER_ON     IR_SONY_POWER_ON
#define REMOTE_POWER_OFF    IR_SONY_POWER_OFF
#define REMOTE_CLEAR        IR_SONY_BACK
#define REMOTE_RED          IR_SONY_RED
#define REMOTE_GREEN        IR_SONY_GREEN
#define REMOTE_YELLOW       IR_SONY_YELLOW
#define REMOTE_BLUE         IR_SONY_BLUE
#define REMOTE_SUBTITLE     IR_SONY_SUBTITLE
#define REMOTE_ASPECT       0

#define REMOTE_F1           0
#define REMOTE_F2           0
#define REMOTE_F3           0
#define REMOTE_F4           0
#define REMOTE_F5           0
#define REMOTE_F6           0
#define REMOTE_F7           0
#define REMOTE_F8           0
